
# ==============================================================================
#                                                                              |
#     Project: IIC Multiple Bus Controller (IICMB)                             |
#                                                                              |
#     Module:  HDL test CI Job for Github.                                     |
#     Version:                                                                 |
#              0.1,   July 17, 2022                                            |
#                                                                              |
#     Author:  Andreas Kaeberlein, (andreas.kaeberlein@web.de)                 |
#                                                                              |
# ==============================================================================
# ==============================================================================
#  Copyright (c) 2016, Sergey Shuvalkin                                        |
#  All rights reserved.                                                        |
#                                                                              |
#  Redistribution and use in source and binary forms, with or without          |
#  modification, are permitted provided that the following conditions are met: |
#                                                                              |
#  1. Redistributions of source code must retain the above copyright notice,   |
#     this list of conditions and the following disclaimer.                    |
#  2. Redistributions in binary form must reproduce the above copyright        |
#     notice, this list of conditions and the following disclaimer in the      |
#     documentation and/or other materials provided with the distribution.     |
#                                                                              |
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" |
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE   |
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  |
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE    |
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR         |
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF        |
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS    |
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN     |
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)     |
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE  |
#  POSSIBILITY OF SUCH DAMAGE.                                                 |
# ==============================================================================



name: HDL

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GHDL_OPTS: "--std=93c --ieee=synopsys --time-resolution=ps --workdir=./sim/work"
    steps:
      - uses: actions/checkout@v1
      - uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: mcode
      - name: Prepare
        run: |
          ghdl --version
          mkdir -p ./sim/work
      - name: iicmb
        run: |
          # Behavior
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/iicmb_pkg.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/iicmb_int_pkg.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/bus_state.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/filter.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/conditioner.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/conditioner_mux.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/mbit.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/mbyte.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/iicmb_m.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/regblock.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/wishbone.vhd
          ghdl -a ${GHDL_OPTS} --work=iicmb --workdir=./sim/work ./src/iicmb_m_wb.vhd
          # Testbench
          #ghdl -a ${GHDL_OPTS} --work=work --workdir=./sim/work ./src_tb/test.vhd
          #ghdl -a ${GHDL_OPTS} --work=work --workdir=./sim/work ./src_tb/wire_mdl.vhd
          #ghdl -a ${GHDL_OPTS} --work=work --workdir=./sim/work -P./sim/iicmb ./src_tb/iicmb_m_tb.vhd
          # Elaborate
          #ghdl -e --work=work --workdir=./sim/work -P./sim/iicmb --syn-binding iicmb_m_tb
          # Run
          #ghdl -r iicmb_m_tb --stop-time=1ms
